run_name: d2_shape_model
dtype: float32

# Data
eval_dataset: "2"
shape: [45, 1, 16, 9]
eval_cut: 15.15e-3

# Preprocessing
transforms:
    NormalizeByElayer:
        ptype: electron
        xml_file: challenge_files/binning_dataset_2.xml
    SelectiveUniformNoise:
        noise_width: 5.0e-6
        cut: True
        exclusions: [-45, -44, -43, -42, -41, -40, -39, -38, -37,
                     -36, -35, -34, -33, -32, -31, -30, -29, -28,
                     -27, -26, -25, -24, -23, -22, -21, -20, -19,
                     -18, -17, -16, -15, -14, -13, -12, -11, -10,
                      -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1]
    ExclusiveLogitTransform:
        delta: 1.e-6
        exclusions: [-45]
    StandardizeFromFile: {}
    LogEnergy: {}
    ScaleEnergy:
        e_min: 6.907755
        e_max: 13.815510
    AddFeaturesToCond:
        split_index: 6480
    Reshape:
        shape: [45, 1, 16, 9]

# Model
model_type: shape
model: TransfusionAR
network: ARtransformer_shape
condition_dim: 46
dim_embedding: 256
n_head: 4
n_encoder_layers: 4
n_decoder_layers: 4
dim_feedforward: 512
normalization: LayerNorm
layer_cond: False
dropout_transformer: 0.02
subnet:
    class: ViT
    params:
        dim: 2
        patch_shape: [4, 3]
        hidden_dim: 96
        depth: 4
        num_heads: 6
        mlp_ratio: 4.0
        pos_embedding_coords: cylindrical
        attn_drop: 0.05
        proj_drop: 0.05

# Sampling
solver_kwargs:
    method: rk4
    options:
        step_size: 0.02
