run_name: ds2
p_type: electron
dtype: float32
# Data
data_path: /remote/gpu06/favaro/datasets/calo_challenge/dataset_2_1.hdf5
val_data_path: /remote/gpu06/favaro/datasets/calo_challenge/dataset_2_2.hdf5
xml_path: /remote/gpu06/favaro/datasets/calo_challenge/binning_dataset_2.xml
single_energy: null
width_noise: 1.0e-6
custom_noise: False
val_frac: 0.1
eps: 1.0e-10
xml_ptype: "electron"
eval_dataset: "2"

# Training
lr: 1.e-5
max_lr: 1.e-4
batch_size: 256

lr_scheduler: one_cycle_lr

weight_decay: 0.01
betas: [0.9, 0.999]
n_epochs: 1
cycle_epochs: 1
save_interval: 100

# Architecture
n_blocks: 14
internal_size: [256, 256, 256]
layers_per_block: 3
coupling_type: cubic
bounds_init: 15
permute_soft: False
permute_layer: False
num_bins: 10
dropout: 0.0
layer_act: nn.LeakyReLU
bayesian: False
prior_prec: 5000
std_init: -15.0

sub_layers: [linear, linear, linear]
norm: True
# Preprocessing
use_extra_dims: True
use_norm: False
log_cond: True
alpha: 1.0e-8
alpha_logit: 1.0e-6
