run_name: d3_vit_fullspace_352_logit_best_full_save
dtype: float32

# Model
model_type: shape
energy_model: /remote/gpu06/favaro/temp/calodream_models/d3_energy_model_AR_logit_full_data_wrescale/

# Data
hdf5_file: /remote/gpu06/favaro/datasets/calo_challenge/dataset_3_1_full.hdf5
eval_hdf5_file: /remote/gpu06/favaro/datasets/calo_challenge/dataset_3_2_full.hdf5
xml_filename: /remote/gpu06/favaro/datasets/calo_challenge/binning_dataset_3.xml

val_frac: 0.00001
eps: 1.0e-10
particle_type: electron
eval_dataset: "3"
eval_cut: 15.15e-3
shape: [1, 45, 50, 18]

transforms: {
    ScaleVoxels: {factor: 0.35},
    NormalizeByElayer: {
        ptype: /remote/gpu06/favaro/datasets/calo_challenge/binning_dataset_3.xml,
        xml_file: electron
    },
    CutValues: {cut: 1.e-7},
    SelectiveUniformNoise: {
        noise_width: 0.0e-5,
        cut: True,
        exclusions: [-45, -44, -43, -42, -41, -40, -39, -38, -37,
                     -36, -35, -34, -33, -32, -31, -30, -29, -28,
                     -27, -26, -25, -24, -23, -22, -21, -20, -19,
                     -18, -17, -16, -15, -14, -13, -12, -11, -10,
                      -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1]
    },
ExclusiveLogitTransform: {delta: 1.0e-6, rescale: True},
    StandardizeFromFile: {},
    LogEnergy: {},
    ScaleEnergy: {e_min: 6.907755, e_max: 13.815510},
    AddFeaturesToCond: {split_index: 40500},
    Reshape: {shape: [1, 45, 50, 18]}
}

# Training
lr: 1.e-3
max_lr: 1.e-3
batch_size: 64
validate_every: 10
use_scheduler: True
lr_scheduler: CosineAnnealing
weight_decay: 1.e-5
betas: [0.9, 0.999]
n_epochs: 125
cycle_epochs: 600
total_epochs: 474
cycle_pct_start: 0.1
save_interval: 100_001
save_periodically: True
save_every: 25
clip_gradients_to: 50

# Sampling
sample_periodically: False
sample_every: 700
sample_every_n_samples: 1001
batch_size_sample: 2000
n_samples: 100000
solver_kwargs: {method: rk4, options: {step_size: 0.02}}

# Network
network: ViT
condition_dim: 46
patch_shape: [3, 5, 2]
hidden_dim: 240
depth: 6
num_heads: 6
mlp_ratio: 3.0
aug_transforms: False
learn_pos_embed: True
cos_attn: False

# patch_shape: [3, 2, 1]
# hidden_dim: 480
# depth: 8
# num_heads: 8
# mlp_ratio: 4.0
