run_name: d2_shape_model_claudius_mlpbitnet
dtype: float32

# Model
model_type: shape
energy_model: /users/claudius.krause/HEP-BitNet/hep-bitnet/examples/results-CaloDREAM/10204744_regular/trained_energy_model/

# Data
hdf5_file: /groups/hephy/mlearning/CaloChallenge/data/official/dataset_2_1.hdf5
eval_hdf5_file: /groups/hephy/mlearning/CaloChallenge/data/official/dataset_2_2.hdf5
xml_filename: /users/claudius.krause/CaloChallenge/CaloChallenge_homepage/code/binning_dataset_2.xml
val_frac: 0.00001
eps: 1.0e-10
particle_type: electron
eval_dataset: "2"
eval_cut: 15.15e-3
shape: [1, 45, 16, 9]

transforms: {
    ScaleVoxels: {factor: 0.35},
    NormalizeByElayer: {
        ptype: /users/claudius.krause/CaloChallenge/CaloChallenge_homepage/code/binning_dataset_2.xml,
        xml_file: electron,
        cut: 1.e-7,
    },
    SelectiveUniformNoise: {
        noise_width: 0.0e-6,
        cut: True,
        exclusions: [-45, -44, -43, -42, -41, -40, -39, -38, -37,
                     -36, -35, -34, -33, -32, -31, -30, -29, -28,
                     -27, -26, -25, -24, -23, -22, -21, -20, -19,
                     -18, -17, -16, -15, -14, -13, -12, -11, -10,
                      -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1]
    },
ExclusiveLogitTransform: {delta: 1.0e-6, rescale: True},
    StandardizeFromFile: {model_dir: ''},
    LogEnergy: {},
    ScaleEnergy: {e_min: 6.907755, e_max: 13.815510},
    AddFeaturesToCond: {split_index: 6480},
    Reshape: {shape: [1, 45, 16, 9]}
}

# Training
lr: 1.e-3
max_lr: 1.e-3
batch_size: 64
validate_every: 5
use_scheduler: True
lr_scheduler: CosineAnnealing
weight_decay: 1.e-5
betas: [0.9, 0.999]
n_epochs: 800
cycle_epochs: 800
cycle_pct_start: 0.1
save_interval: 100_001
clip_gradients_to: 100

# Sampling
sample_periodically: False
sample_every: 10
sample_every_n_samples: 1001
batch_size_sample: 10000
n_samples: 100000
solver_kwargs: {method: rk4, options: {step_size: 0.05}}

# Network
network: ViT
condition_dim: 46
patch_shape: [3, 16, 1]
hidden_dim: 480
depth: 6
num_heads: 6
mlp_ratio: 4.0
augment_batch: False
pos_embedding_coords: cylindrical
learn_pos_embed: True
cos_attn: False
use_bitnet_shape: mlp

# patch_shape: [3, 2, 1]
# hidden_dim: 480
# depth: 8
# num_heads: 8
# mlp_ratio: 4.0
